# Generated by Django 4.1.3 on 2022-12-07 04:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('student_management_app', '0003_alter_course_c_time'),
    ]

    operations = [
        migrations.AlterField(
            model_name='course',
            name='C_time',
            field=models.DateField(),
        ),
    ]
