# Generated by Django 4.1.3 on 2022-12-07 05:39

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('student_management_app', '0004_alter_course_c_time'),
    ]

    operations = [
        migrations.AlterField(
            model_name='course',
            name='T_id',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='student_management_app.teacher', to_field='T_number'),
        ),
    ]
