# Generated by Django 4.1.3 on 2022-12-07 10:05

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('student_management_app', '0005_alter_course_t_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='student',
            name='S_major',
            field=models.CharField(max_length=100),
        ),
        migrations.AlterField(
            model_name='student',
            name='S_name',
            field=models.CharField(max_length=100),
        ),
        migrations.AlterField(
            model_name='student',
            name='S_number',
            field=models.CharField(max_length=50, unique=True, validators=[django.core.validators.MinLengthValidator(50)]),
        ),
        migrations.AlterField(
            model_name='teacher',
            name='T_number',
            field=models.CharField(max_length=50, unique=True, validators=[django.core.validators.MinLengthValidator(50)]),
        ),
    ]
